### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by archasek** [Zebreus/replicate-api#1]
Hey, I have similar problems with config mentioned here: https://github.com/nicholascelestin/replicate-js/issues/11#issuecomment-1418270225

Can you please provide your working tsconfig settings?

Temporarily I just hard copied the lib into my project and changed all paths to contain `./` at the beginning and it's working. However, it's a workaround.

**Comment by zebreus** [comment]
I will look into it. When I wrote this project, I thought it would be a good idea to use imports relative to the `src` folder and resolve them in the build step. Probably has something to do with this.

Can you share your errors, or even better an example?

**Comment by zebreus** [comment]
I created a quick example with a working tsconfig, which you can try out on gitpod at https://gitpod.io/#https://github.com/zebreus/replicate-test .

I am pretty sure, that that is not a problem with my package, but with `ts-node-dev`. wclr/ts-node-dev#314 seems to have the same issue, but I do not think it is going to be fixed, because `ts-node-dev` seems pretty dead.

I recommend using `tsx` as a replacement, should be as simple as `tsx watch src/app.ts`.

**Comment by archasek** [comment]
Great suggestion with `tsx`, works like a charm. 

Like I mentioned you pointed out, with `ts-node`/`ts-node-dev` and `nodemon` there were lots of problems, but some of them could be probably able to be overcome with changing all imports to have `.js` suffix, as I've been mainly receiving:
```
throw new ERR_MODULE_NOT_FOUND(
          ^
CustomError: Cannot find module 'requestRouter' imported from ...\src\app.ts`).
```

Thanks a lot! And thank you @zebreus for a cool lib 😺!

**Comment by zebreus** [comment]
The imports actually have their paths resolved to relative paths with suffixes during the build step, so that should not be the problem (at least in this lib). Maybe they also require suffixes in the `.d.ts` files, but I dont think so, as they should only be parsed by typescript which does not require the file extensions.
